const settings=JSON.parse(localStorage.getItem('aryoneSettings')||localStorage.getItem('y2Settings')||'{}'),AUTOPLAY=settings.autoplay!==false;
if(settings.accent)document.documentElement.style.setProperty('--blue',settings.accent);
const sourceMatches=Array.isArray(window.ARYONE_FOOTBALL_MATCHES)?window.ARYONE_FOOTBALL_MATCHES:[];
const state={matches:[],filter:'all',activeMatchId:null,activeUrl:null,activeLabel:null};
const list=document.querySelector('#matches'),updated=document.querySelector('#updated'),count=document.querySelector('#count'),toast=document.querySelector('#toast'),modal=document.querySelector('#playerModal'),video=document.querySelector('#videoPlayer'),playerTitle=document.querySelector('#playerTitle'),streamStatus=document.querySelector('#streamStatus'),videoLoading=document.querySelector('#videoLoading'),qualityWrap=document.querySelector('#qualityWrap'),qualityList=document.querySelector('#qualityList');let hls=null;const plyr=window.Plyr?new Plyr(video,{controls:['play-large','play','progress','current-time','mute','volume','settings','pip','fullscreen'],fullscreen:{enabled:true,fallback:true,iosNative:false,container:'#videoWrap'},hideControls:true,resetOnEnd:false}):null;
const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const logo=(url,name)=>url?`<img class="logo" src="${safe(url)}" alt="${safe(name)} logo" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="fa-icon-fallback" style="display:none"><i class="fa-solid fa-shield-halved"></i></span>`:`<span class="fa-icon-fallback"><i class="fa-solid fa-shield-halved"></i></span>`;
function normalizeStreams(m){const raw=Array.isArray(m.streams)?m.streams:[];const streams=raw.map((s,i)=>typeof s==='string'?{label:`SERVER ${i+1}`,url:s}:{label:s.label||s.quality||`SERVER ${i+1}`,url:s.url||s.stream||''}).filter(s=>s.url);if(!streams.length&&m.stream)streams.push({label:'LIVE',url:m.stream});return streams}
function normalize(m){const kickoff=new Date(m.kickoff),now=Date.now(),autoLive=kickoff.getTime()<=now&&now<kickoff.getTime()+135*60000,live=m.status==='live'||m.status==='auto'&&autoLive;return{...m,id:String(m.id),league:m.league||'Football',home:m.home||'Home',away:m.away||'Away',homeLogo:m.homeLogo||'',awayLogo:m.awayLogo||'',homeScore:m.homeScore??'–',awayScore:m.awayScore??'–',live,time:live?'LIVE':kickoff.toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}),streams:normalizeStreams(m)}}
function loadMatches(){state.matches=sourceMatches.map(normalize);render();updated.textContent=`GitHub custom matches • ${state.matches.length} ပွဲ`}
function visible(){return state.filter==='live'?state.matches.filter(m=>m.live):state.filter==='upcoming'?state.matches.filter(m=>!m.live):state.matches}
function render(){const games=visible();count.textContent=games.length;if(!games.length){list.innerHTML='<div class="empty"><b>ပွဲစဉ်မရှိသေးပါ</b><code>custom-matches.js</code> ထဲမှာ ပွဲစဉ်ထည့်ပြီး GitHub ကို upload လုပ်ပါ။</div>';return}list.innerHTML=games.map(m=>`<article class="match" data-match-id="${safe(m.id)}"><div class="league"><span class="trophy"><i class="fa-solid fa-trophy"></i></span><span>${safe(m.league)}</span><button class="bell" data-id="${safe(m.id)}"><i class="fa-regular fa-bell"></i></button><span class="match-time ${m.live?'live':''}">${safe(m.time)}</span></div><div class="team">${logo(m.homeLogo,m.home)}<span>${safe(m.home)}</span><b class="score">${safe(m.homeScore)}</b></div><div class="team">${logo(m.awayLogo,m.away)}<span>${safe(m.away)}</span><b class="score">${safe(m.awayScore)}</b></div></article>`).join('')}
function setActiveQuality(url){qualityList.querySelectorAll('.quality-button').forEach(b=>b.classList.toggle('active',b.dataset.url===url))}
function playSource(url,label='LIVE'){if(!url||state.activeUrl===url)return;state.activeUrl=url;state.activeLabel=label;setActiveQuality(url);videoLoading.classList.remove('hide');if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load();video.autoplay=AUTOPLAY;if(url.toLowerCase().includes('.m3u8')){if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true});hls.loadSource(url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{if(AUTOPLAY)video.play().catch(()=>{})});hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal){videoLoading.classList.add('hide');streamStatus.textContent=`${label} stream ဖွင့်မရပါ။ အခြား quality တစ်ခုရွေးပါ။`}})}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=url;if(AUTOPLAY)video.play().catch(()=>{})}else{videoLoading.classList.add('hide');streamStatus.textContent='ဒီ browser က HLS stream ကို support မလုပ်ပါ။'}}else{video.src=url;if(AUTOPLAY)video.play().catch(()=>{})}streamStatus.textContent=`${label} stream ကို ဖွင့်ထားပါသည်။`}
function openPlayer(m){state.activeMatchId=m.id;state.activeUrl=null;state.activeLabel=null;playerTitle.textContent=`${m.home} vs ${m.away}`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';qualityList.innerHTML=m.streams.map((s,i)=>`<button class="quality-button${i===0?' active':''}" data-url="${safe(s.url)}" data-label="${safe(s.label)}"><i class="fa-solid ${/fhd|1080/i.test(s.label)?'fa-tv':/hd|720/i.test(s.label)?'fa-display':'fa-signal'}"></i>${safe(s.label)}</button>`).join('');qualityWrap.classList.toggle('show',m.streams.length>1);if(m.streams.length){video.style.display='block';playSource(m.streams[0].url,m.streams[0].label)}else{if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load();video.style.display='none';videoLoading.classList.add('hide');qualityWrap.classList.remove('show');streamStatus.textContent='ဒီပွဲအတွက် Stream URL မရှိသေးပါ။'}}
function closePlayer(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';state.activeMatchId=null;if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load()}
video.onplaying=()=>videoLoading.classList.add('hide');video.onwaiting=()=>videoLoading.classList.remove('hide');
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelector('.tab.active').classList.remove('active');b.classList.add('active');state.filter=b.dataset.filter;render()});
list.onclick=e=>{const bell=e.target.closest('.bell');if(bell){bell.classList.toggle('on');bell.innerHTML=bell.classList.contains('on')?'<i class="fa-solid fa-bell"></i>':'<i class="fa-regular fa-bell"></i>';return}const card=e.target.closest('.match');if(card){const m=state.matches.find(x=>x.id===card.dataset.matchId);if(m)openPlayer(m)}};
document.querySelector('#closePlayer').onclick=closePlayer;modal.onclick=e=>{if(e.target===modal)closePlayer()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closePlayer()});loadMatches();setInterval(loadMatches,30000);
qualityList.onclick=e=>{const button=e.target.closest('.quality-button');if(button)playSource(button.dataset.url,button.dataset.label)};
document.querySelector('#refreshMatches').onclick=e=>{const button=e.currentTarget;button.disabled=true;button.querySelector('i').classList.add('fa-spin');loadMatches();toast.textContent='ပွဲစဉ်များ Refresh လုပ်ပြီးပါပြီ';toast.classList.add('show');setTimeout(()=>{button.disabled=false;button.querySelector('i').classList.remove('fa-spin');toast.classList.remove('show')},900)};
document.querySelector('#playerBack').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else if(plyr?.fullscreen?.active)plyr.fullscreen.exit();else closePlayer()};
