// Generated by AR YONE Match Admin
// TODAY: 01 September 2026
// Timezone: Myanmar Time (MMT / UTC+06:30)

window.ARYONE_FOOTBALL_MATCHES = [
  {
    id: "match-01",
    league: "ENGLAND PREMIER LEAGUE",
    home: "ASTON VILLA",
    away: "ARSENAL",
    homeLogo: "https://upload.wikimedia.org/wikipedia/en/9/9f/Aston_Villa_FC_new_crest.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
    kickoff: "2026-09-01T01:30:00+06:30",
    status: "auto",
    streams: [
      {
        label: "HD",
        url: "https://live05.meung.app/live/33982309.m3u8"
      },
      {
        label: "HD-2",
        url: "https://live05.meung.app/live/02456966.m3u8"
      },
      {
        label: "HD-3",
        url: "https://live05.meung.app/live/97885009.m3u8"
      },
      {
        label: "FHD",
        url: "https://hls.lauthaitv.cc/live/ast-ars-prem/index.m3u8"
      }
    ]
  },

  {
    id: "match-02",
    league: "SPAIN LALIGA",
    home: "FC BARCELONA",
    away: "RAYO VALLECANO",
    homeLogo: "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/1/1c/Rayo_Vallecano_logo.svg",
    kickoff: "2026-09-01T02:30:00+06:30",
    status: "auto",
    streams: []
  }
];
