// Generated by AR YONE Match Admin
window.ARYONE_FOOTBALL_MATCHES = [
  {
    id: "ucl-01",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "AEK ATHENS",
    away: "LASK LINZ",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/5/53/AEK_FC_crest.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/7/7b/LASK_Linz_logo.svg",

    kickoff: "2026-09-08T23:15:00+06:30",
    status: "auto",

    streams: [
      {
        label: "FHD",
        url: "https://hls.lauthaitv.cc/live/aek-lask-c12/index.m3u8"
      },
      {
        label: "HD",
        url: "https://live05.meung.app/live/02456966.m3u8"
      },
      {
        label: "HD-2",
        url: "https://live05.meung.app/live/97885009.m3u8"
      }
    ]
  },

  {
    id: "ucl-02",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "CLUB BRUGGE",
    away: "ASTON VILLA",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/d/d0/Club_Brugge_KV_logo.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/f/f9/Aston_Villa_FC_new_crest.svg",

    kickoff: "2026-09-08T23:15:00+06:30",
    status: "auto",

    streams: [
      {
        label: "FHD",
        url: "https://hls.lauthaitv.cc/live/brugge-aston-ucl2/index.m3u8"
      },
      {
        label: "HD",
        url: "https://live05.meung.app/live/08552895.m3u8"
      },
      {
        label: "HD-2",
        url: "https://live05.meung.app/live/33982309.m3u8"
      },
      {
        label: "HD-3",
        url: "https://live05.meung.app/live/33982309.m3u8"
      }
    ]
  },

  {
    id: "ucl-03",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "BORUSSIA DORTMUND",
    away: "VILLARREAL",

    homeLogo: "https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/7/70/Villarreal_CF_logo.svg",

    kickoff: "2026-09-09T01:30:00+06:30",
    status: "auto",

    streams: [
      {
        label: "HD",
        url: "https://live05.meung.app/live/87379114.m3u8?_t=1788892768987"
      },
      {
        label: "HD-2",
        url: "https://live05.meung.app/live/02456966.m3u8?_t=1788892786135"
      },
      {
        label: "Chinese HD",
        url: "https://hwyypull.ncctrials.com/live/stream-238362_lhd.m3u8?auth_key=1788896626-0-0-27bea3fe52abb990ce8e45fe6a33dce1"
      },
      {
        label: "Chinese SD",
        url: "https://hwyypull.ncctrials.com/live/stream-238362_lsd.m3u8?auth_key=1788896626-0-0-0014956fee2cb5b112fdf0b6e978bf6b"
      },
      {
        label: "FHD",
        url: "https://hls.lauthaitv.cc/live/dortmund-villarreal-c1/index.m3u8"
      }
    ]
  },

  {
    id: "ucl-04",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "FC PORTO",
    away: "MANCHESTER CITY",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",

    kickoff: "2026-09-09T01:30:00+06:30",
    status: "auto",

    streams: [
      {
        label: "HD",
        url: "https://live05.meung.app/live/33982309.m3u8?_t=1788892836749"
      },
      {
        label: "HD-2",
        url: "https://live05.meung.app/live/14707124.m3u8?_t=1788892865684"
      },
      {
        label: "Chinese HD",
        url: "https://hwyypull.ncctrials.com/live/stream-727148_lhd.m3u8?auth_key=1788896628-0-0-be5a6304e267fd858386b27705358d01"
      },
      {
        label: "Chinese SD",
        url: "https://hwyypull.ncctrials.com/live/stream-727148_lsd.m3u8?auth_key=1788896628-0-0-cb3390d91ebf8ef58be0d95876d10088"
      },
      {
        label: "FHD",
        url: "https://hls.lauthaitv.cc/live/porto-manc-c1/index.m3u8"
      }
    ]
  },

  {
    id: "ucl-05",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "LILLE",
    away: "REAL BETIS",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/3/3f/Lille_OSC_2018_logo.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/1/13/Real_betis_logo.svg",

    kickoff: "2026-09-09T01:30:00+06:30",
    status: "auto",

    streams: [
      {
        label: "HD",
        url: "https://live05.meung.app/live/90865415.m3u8?_t=1788892916663"
      },
      {
        label: "HD-2",
        url: "https://live05.meung.app/live/97885009.m3u8?_t=1788892937464"
      },
      {
        label: "Chinese HD",
        url: "https://pull.qjkngv.com/live/stream-578718_lhd.m3u8?auth_key=1788896683-0-0-d54c9b64c9e4f545335d319dfc9af07b"
      },
      {
        label: "Chinese SD",
        url: "https://pull.qjkngv.com/live/stream-578718_lsd.m3u8?auth_key=1788896683-0-0-e3bf6a0eae67bb31929ef0e33eab24f8"
      }
    ]
  },

  {
    id: "ucl-06",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "REAL MADRID",
    away: "INTER MILAN",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg",

    kickoff: "2026-09-09T01:30:00+06:30",
    status: "auto",

    streams: [
      {
        label: "HD",
        url: "https://live05.meung.app/live/08552895.m3u8?_t=1788892669462"
      },
      {
        label: "HD-2",
        url: "https://live05.meung.app/live/14830711.m3u8?_t=1788892969376"
      },
      {
        label: "Chinese HD",
        url: "https://hwyypull.ncctrials.com/live/stream-746673_lhd.m3u8?auth_key=1788896628-0-0-6fc9259f80fde10aaa51645913e74e5e"
      },
      {
        label: "Chinese SD",
        url: "https://hwyypull.ncctrials.com/live/stream-746673_lsd.m3u8?auth_key=1788896628-0-0-e5238664f571696d09650bf97465ab10"
      },
      {
        label: "FHD",
        url: "https://hls.lauthaitv.cc/live/real-inter-c1/index.m3u8"
      }
    ]
  },

  {
    id: "ucl-07",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "BARCELONA",
    away: "FEYENOORD",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/8/8d/Feyenoord_logo.svg",

    kickoff: "2026-09-09T23:15:00+06:30",
    status: "auto",

    streams: []
  },

  {
    id: "ucl-08",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "VFB STUTTGART",
    away: "VIKING FK",

    homeLogo: "https://upload.wikimedia.org/wikipedia/commons/e/eb/VfB_Stuttgart_1893_Logo.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/4/4c/Viking_FK_logo.svg",

    kickoff: "2026-09-09T23:15:00+06:30",
    status: "auto",

    streams: []
  },

  {
    id: "ucl-09",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "LIVERPOOL",
    away: "ATLETICO MADRID",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg",

    kickoff: "2026-09-10T01:30:00+06:30",
    status: "auto",

    streams: []
  },

  {
    id: "ucl-10",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "PARIS SAINT-GERMAIN",
    away: "SLOVAN BRATISLAVA",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/9/92/%C5%A0K_Slovan_Bratislava_logo.svg",

    kickoff: "2026-09-10T01:30:00+06:30",
    status: "auto",

    streams: []
  },

  {
    id: "ucl-11",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "SPORTING CP",
    away: "GALATASARAY",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/3/3e/Sporting_Clube_de_Portugal_%28Logo%29.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/3/36/Galatasaray_Sports_Club_Logo.svg",

    kickoff: "2026-09-10T01:30:00+06:30",
    status: "auto",

    streams: []
  },

  {
    id: "ucl-12",
    league: "UEFA CHAMPIONS LEAGUE",
    home: "NAPOLI",
    away: "ARSENAL",

    homeLogo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Napoli_Logo.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",

    kickoff: "2026-09-10T01:30:00+06:30",
    status: "auto",

    streams: []
  }
];
