// Generated by AR YONE Match Admin
window.ARYONE_FOOTBALL_MATCHES = [
  {
    id: "juventus-milan-01",
    league: "ITALIAN SERIE A",
    home: "JUVENTUS",
    away: "AC MILAN",

    homeLogo: "https://upload.wikimedia.org/wikipedia/en/0/0b/Juventus_FC_2017_logo.svg",
    awayLogo: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg",

    kickoff: "2026-09-07T01:15:00+06:30",
    status: "auto",

    streams: [
      {
        label: "FHD",
        url: "https://hls.lauthaitv.cc/live/juv-acmilan-seriea/index.m3u8"
      }
    ]
  }
];
