const NEWS_API='https://site.api.espn.com/apis/site/v2/sports/soccer/all/news?limit=50';
let articles=[],category='All';
const breaking=document.querySelector('#breaking'),grid=document.querySelector('#newsGrid'),categories=document.querySelector('#newsCategories'),search=document.querySelector('#newsSearch'),updated=document.querySelector('#newsUpdated'),count=document.querySelector('#newsCount'),toast=document.querySelector('#toast');
const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function say(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
function normalize(a){const cats=(a.categories||[]).map(c=>c.description||c.type||c.sportId).filter(Boolean);return{id:a.id,title:a.headline||'Football News',description:a.description||'',image:a.images?.[0]?.url||'',url:a.links?.web?.href||'#',published:a.published||a.lastModified,byline:a.byline||'Football News',categories:cats.length?cats:['Football']}}
function ago(value){const seconds=Math.max(1,(Date.now()-new Date(value).getTime())/1000);if(seconds<3600)return`${Math.floor(seconds/60)}m ago`;if(seconds<86400)return`${Math.floor(seconds/3600)}h ago`;return`${Math.floor(seconds/86400)}d ago`}
function visible(){const q=search.value.trim().toLowerCase();return articles.filter(a=>(category==='All'||a.categories.includes(category))&&(`${a.title} ${a.description}`.toLowerCase().includes(q)))}
function renderCategories(){const names=['All',...new Set(articles.flatMap(a=>a.categories))].slice(0,9);categories.innerHTML=names.map(c=>`<button class="news-category ${c===category?'active':''}" data-category="${safe(c)}">${safe(c)}</button>`).join('')}
function render(){const items=visible();count.textContent=items.length;if(!items.length){grid.innerHTML='<div class="news-empty"><b>သတင်းမတွေ့ပါ</b>Search သို့မဟုတ် category ပြောင်းကြည့်ပါ။</div>';return}grid.innerHTML=items.slice(1).map(a=>`<a class="news-card" href="${safe(a.url)}" target="_blank" rel="noopener"><div class="news-image">${a.image?`<img src="${safe(a.image)}" alt="" loading="lazy">`:''}<span>${safe(a.categories[0])}</span></div><div class="news-copy"><h3>${safe(a.title)}</h3><p>${safe(a.description)}</p><div class="news-meta"><span>${safe(ago(a.published))}</span><span>•</span><span>${safe(a.byline)}</span></div></div></a>`).join('')}
function renderBreaking(){const a=articles[0];if(!a){breaking.innerHTML='<div class="news-loading">Breaking news မရှိသေးပါ</div>';return}breaking.innerHTML=`${a.image?`<img src="${safe(a.image)}" alt="">`:''}<a class="breaking-link" href="${safe(a.url)}" target="_blank" rel="noopener" aria-label="Read article"></a><div class="breaking-copy"><span>BREAKING</span><h2>${safe(a.title)}</h2><p>${safe(a.description)}</p></div>`}
async function load(manual=false){try{const response=await fetch(`${NEWS_API}&_=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error('API');const data=await response.json();articles=(data.articles||[]).map(normalize);renderBreaking();renderCategories();render();updated.textContent=`နောက်ဆုံး update • ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`;if(manual)say('သတင်းများ update လုပ်ပြီးပါပြီ')}catch(e){breaking.innerHTML='<div class="news-loading">News feed ယာယီမရနိုင်ပါ</div>';grid.innerHTML='<div class="news-empty"><b>သတင်းမရနိုင်ပါ</b>Internet connection စစ်ပြီး Refresh နှိပ်ပါ။</div>';updated.textContent='Connection error'}}
categories.onclick=e=>{const b=e.target.closest('.news-category');if(!b)return;category=b.dataset.category;renderCategories();render()};search.oninput=render;document.querySelector('#newsRefresh').onclick=()=>load(true);load();setInterval(load,300000);
