const SCORE_API='https://site.api.espn.com/apis/site/v2/sports/soccer/all/scoreboard';
let selectedDate=new Date(),statusFilter='all',events=[];
const list=document.querySelector('#scoreList'),dateInput=document.querySelector('#scoreDate'),dateLabel=document.querySelector('#dateLabel'),updated=document.querySelector('#scoreUpdated'),count=document.querySelector('#scoreCount'),toast=document.querySelector('#toast');
const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const apiDate=d=>localDate(d).replaceAll('-','');
function say(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
function normalize(event){const game=event.competitions?.[0]||{},teams=game.competitors||[],home=teams.find(t=>t.homeAway==='home')||teams[0]||{},away=teams.find(t=>t.homeAway==='away')||teams[1]||{},type=event.status?.type||{},state=type.state||'pre';return{id:event.id,league:event.season?.slug?.replaceAll('-',' ')||'World Football',leagueLogo:'',home:home.team?.displayName||'Home',away:away.team?.displayName||'Away',homeLogo:home.team?.logo||'',awayLogo:away.team?.logo||'',homeScore:home.score??'0',awayScore:away.score??'0',state,detail:state==='in'?(event.status?.displayClock||type.shortDetail||'LIVE'):state==='post'?'FT':new Date(event.date).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),homeWinner:Boolean(home.winner),awayWinner:Boolean(away.winner)}}
function filtered(){return events.filter(e=>statusFilter==='all'||statusFilter==='live'&&e.state==='in'||statusFilter==='finished'&&e.state==='post'||statusFilter==='upcoming'&&e.state==='pre')}
function teamLogo(url,name){return url?`<img src="${safe(url)}" alt="" loading="lazy">`:`<span class="team-dot">${safe(name[0])}</span>`}
function render(){const games=filtered();count.textContent=games.length;if(!games.length){list.innerHTML='<div class="score-empty"><b>ပွဲစဉ်မရှိပါ</b>အခြား date သို့မဟုတ် filter ရွေးကြည့်ပါ။</div>';return}const groups=Object.groupBy?Object.groupBy(games,g=>g.league):games.reduce((a,g)=>((a[g.league]??=[]).push(g),a),{});list.innerHTML=Object.entries(groups).map(([league,items])=>`<article class="league-group"><header class="league-head"><span>🏆</span><span>${safe(league)}</span></header>${items.map(g=>`<div class="score-game"><div class="game-status ${g.state==='in'?'live':''}">${safe(g.detail)}</div><div class="game-teams"><div class="game-team">${teamLogo(g.homeLogo,g.home)}<span>${safe(g.home)}</span></div><div class="game-team">${teamLogo(g.awayLogo,g.away)}<span>${safe(g.away)}</span></div></div><div class="game-scores"><b class="${g.homeWinner?'winner':'loser'}">${safe(g.homeScore)}</b><b class="${g.awayWinner?'winner':'loser'}">${safe(g.awayScore)}</b></div></div>`).join('')}</article>`).join('')}
function syncDate(){dateInput.value=localDate(selectedDate);const today=localDate(new Date()),tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);dateLabel.textContent=localDate(selectedDate)===today?'TODAY':localDate(selectedDate)===localDate(tomorrow)?'TOMORROW':localDate(selectedDate)===localDate(yesterday)?'YESTERDAY':selectedDate.toLocaleDateString([], {weekday:'short'}).toUpperCase()}
async function load(manual=false){updated.textContent='ရလဒ်များ update လုပ်နေပါသည်…';try{const response=await fetch(`${SCORE_API}?dates=${apiDate(selectedDate)}&_=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error('API');const data=await response.json();events=(data.events||[]).map(normalize);render();updated.textContent=`နောက်ဆုံး update • ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`;if(manual)say('ရလဒ်များ update လုပ်ပြီးပါပြီ')}catch(e){list.innerHTML='<div class="score-empty"><b>ရလဒ်များ ယာယီမရနိုင်ပါ</b>Internet connection စစ်ပြီး ပြန်စမ်းပါ။</div>';updated.textContent='Connection error';count.textContent='0'}}
document.querySelectorAll('.score-tabs button').forEach(b=>b.onclick=()=>{document.querySelector('.score-tabs .active').classList.remove('active');b.classList.add('active');statusFilter=b.dataset.status;render()});
document.querySelector('#prevDate').onclick=()=>{selectedDate.setDate(selectedDate.getDate()-1);syncDate();load()};document.querySelector('#nextDate').onclick=()=>{selectedDate.setDate(selectedDate.getDate()+1);syncDate();load()};dateInput.onchange=()=>{selectedDate=new Date(`${dateInput.value}T12:00:00`);syncDate();load()};document.querySelector('#scoreRefresh').onclick=()=>load(true);syncDate();load();setInterval(()=>load(),30000);
