const defaults=window.ARYONE_DEFAULT_GAMES||[],savedGames=JSON.parse(localStorage.getItem('aryoneGames')||'[]');let games=[...defaults,...savedGames],filter='အားလုံး',hls=null;
const grid=document.querySelector('#gamesGrid'),filters=document.querySelector('#sportFilters'),search=document.querySelector('#gameSearch'),video=document.querySelector('#gameVideo'),player=document.querySelector('#sportsPlayer'),placeholder=document.querySelector('#gamePlaceholder'),loader=document.querySelector('#gameLoader'),playingTitle=document.querySelector('#playingTitle'),playingMeta=document.querySelector('#playingMeta'),modal=document.querySelector('#gameModal'),toast=document.querySelector('#toast');
const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function say(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
function renderFilters(){const items=['အားလုံး',...new Set(games.map(g=>g.sport||'အခြား'))];filters.innerHTML=items.map(s=>`<button class="sport-filter ${s===filter?'active':''}" data-sport="${safe(s)}">${safe(s)}</button>`).join('')}
function render(){const q=search.value.trim().toLowerCase(),items=games.filter(g=>(filter==='အားလုံး'||g.sport===filter)&&`${g.name} ${g.team1} ${g.team2}`.toLowerCase().includes(q));document.querySelector('#gameCount').textContent=`${items.length} games`;grid.innerHTML=items.map(g=>`<article class="game-card" data-id="${safe(g.id)}">${g.custom?'<button class="delete-game" aria-label="Delete game"><i class="fa-solid fa-trash-can"></i></button>':''}<div class="game-banner" ${g.image?`style="background-image:url('${safe(g.image)}')"`:''}><span class="sport-name">${safe(g.sport)}</span><h3>${safe(g.name)}</h3><div class="versus">${safe(g.team1)} &nbsp; VS &nbsp; ${safe(g.team2)}</div></div><div class="game-footer"><span><i class="fa-regular fa-clock"></i> ${safe(g.time||'LIVE NOW')}</span><button class="watch-game">ကြည့်မည် <i class="fa-solid fa-play"></i></button></div></article>`).join('')||'<div class="empty"><b>ပွဲစဉ်မရှိပါ</b><i class="fa-solid fa-plus"></i> ခလုတ်ကနေ ပွဲအသစ်ထည့်ပါ။</div>'}
function play(g){player.classList.add('open');playingTitle.textContent=g.name;playingMeta.textContent=`${g.team1} vs ${g.team2} • ${g.sport}`;placeholder.style.display='none';loader.classList.add('show');if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');if(g.url.toLowerCase().includes('.m3u8')){if(window.Hls&&Hls.isSupported()){hls=new Hls();hls.loadSource(g.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>video.play().catch(()=>{}));hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal){loader.classList.remove('show');say('Stream ဖွင့်မရပါ')}})}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=g.url;video.play().catch(()=>{})}else say('Browser က HLS support မလုပ်ပါ')}else{video.src=g.url;video.play().catch(()=>{})}player.scrollIntoView({behavior:'smooth',block:'start'})}
video.onplaying=()=>loader.classList.remove('show');video.onwaiting=()=>loader.classList.add('show');filters.onclick=e=>{const b=e.target.closest('.sport-filter');if(!b)return;filter=b.dataset.sport;renderFilters();render()};search.oninput=render;
grid.onclick=e=>{const card=e.target.closest('.game-card');if(!card)return;const game=games.find(g=>String(g.id)===card.dataset.id);if(e.target.closest('.delete-game')){const next=JSON.parse(localStorage.getItem('aryoneGames')||'[]').filter(g=>String(g.id)!==card.dataset.id);localStorage.setItem('aryoneGames',JSON.stringify(next));games=[...defaults,...next];renderFilters();render();say('ပွဲစဉ် ဖျက်ပြီးပါပြီ');return}if(game)play(game)};
document.querySelector('#addGame').onclick=()=>modal.classList.add('open');document.querySelector('#closeGameForm').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
document.querySelector('#gameForm').onsubmit=e=>{e.preventDefault();const item={id:`game-${Date.now()}`,name:document.querySelector('#gameName').value.trim(),team1:document.querySelector('#teamOne').value.trim(),team2:document.querySelector('#teamTwo').value.trim(),url:document.querySelector('#gameUrl').value.trim(),image:document.querySelector('#gameImage').value.trim(),sport:document.querySelector('#gameSport').value,time:document.querySelector('#gameTime').value.trim()||'LIVE NOW',custom:true},next=[...JSON.parse(localStorage.getItem('aryoneGames')||'[]'),item];localStorage.setItem('aryoneGames',JSON.stringify(next));games=[...defaults,...next];e.target.reset();modal.classList.remove('open');renderFilters();render();say('ပွဲစဉ် ထည့်ပြီးပါပြီ')};document.querySelector('#gameFullscreen').onclick=()=>document.querySelector('.sports-screen').requestFullscreen?.();renderFilters();render();
