const defaults=window.ARYONE_DEFAULT_CHANNELS||[],custom=JSON.parse(localStorage.getItem('aryoneChannels')||localStorage.getItem('y2Channels')||'[]');
let channels=[...defaults,...custom],filter='All',hls=null;
const grid=document.querySelector('#channelGrid'),categories=document.querySelector('#categories'),search=document.querySelector('#search'),video=document.querySelector('#tvVideo'),placeholder=document.querySelector('#placeholder'),loader=document.querySelector('#loader'),title=document.querySelector('#nowTitle'),nowCategory=document.querySelector('#nowCategory'),modal=document.querySelector('#channelModal'),toast=document.querySelector('#toast');
const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function say(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
function renderCategories(){const items=['All',...new Set(channels.map(c=>c.category||'Other'))];categories.innerHTML=items.map(c=>`<button class="category ${c===filter?'active':''}" data-category="${safe(c)}">${safe(c)}</button>`).join('')}
function render(){const q=search.value.trim().toLowerCase(),items=channels.filter(c=>(filter==='All'||c.category===filter)&&c.name.toLowerCase().includes(q));document.querySelector('#channelCount').textContent=`${items.length} channels`;grid.innerHTML=items.map(c=>`<article class="channel-card" data-id="${safe(c.id)}">${c.custom?'<button class="delete-channel" title="Delete">×</button>':''}<div class="channel-art">${c.logo?`<img src="${safe(c.logo)}" alt="" onerror="this.outerHTML='<span class=letter>TV</span>'">`:`<span class="letter">${safe(c.name.slice(0,2).toUpperCase())}</span>`}</div><div class="channel-info"><b>${safe(c.name)}</b><small>${safe(c.category||'Other')} • Live</small></div></article>`).join('')||'<div class="empty"><b>Channel မတွေ့ပါ</b>Search ပြောင်းကြည့်ပါ။</div>'}
function play(channel){title.textContent=channel.name;nowCategory.textContent=`${channel.category||'Other'} • Live Stream`;placeholder.style.display='none';loader.classList.add('show');if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');if(channel.url.toLowerCase().includes('.m3u8')){if(window.Hls&&Hls.isSupported()){hls=new Hls();hls.loadSource(channel.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>video.play().catch(()=>{}));hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal){loader.classList.remove('show');say('Stream ဖွင့်မရပါ')}})}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=channel.url;video.play().catch(()=>{})}else say('HLS ကို browser က support မလုပ်ပါ')}else{video.src=channel.url;video.play().catch(()=>{})}}
video.onplaying=()=>loader.classList.remove('show');video.onwaiting=()=>loader.classList.add('show');
categories.onclick=e=>{const b=e.target.closest('.category');if(!b)return;filter=b.dataset.category;renderCategories();render()};search.oninput=render;
grid.onclick=e=>{const card=e.target.closest('.channel-card');if(!card)return;const channel=channels.find(c=>String(c.id)===card.dataset.id);if(e.target.closest('.delete-channel')){const next=custom.filter(c=>String(c.id)!==card.dataset.id);localStorage.setItem('aryoneChannels',JSON.stringify(next));channels=[...defaults,...next];renderCategories();render();say('Channel ဖျက်ပြီးပါပြီ');return}if(channel)play(channel)};
document.querySelector('#addChannel').onclick=()=>modal.classList.add('open');document.querySelector('#closeForm').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
document.querySelector('#channelForm').onsubmit=e=>{e.preventDefault();const item={id:`custom-${Date.now()}`,name:document.querySelector('#channelName').value.trim(),url:document.querySelector('#channelUrl').value.trim(),logo:document.querySelector('#channelLogo').value.trim(),category:document.querySelector('#channelCategory').value,custom:true};const next=[...JSON.parse(localStorage.getItem('aryoneChannels')||'[]'),item];localStorage.setItem('aryoneChannels',JSON.stringify(next));channels=[...defaults,...next];e.target.reset();modal.classList.remove('open');renderCategories();render();say('Channel ထည့်ပြီးပါပြီ')};
document.querySelector('#fullscreen').onclick=()=>document.querySelector('.tv-screen').requestFullscreen?.();renderCategories();render();
